# Generated by Django 2.0 on 2017-12-24 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeType', models.CharField(max_length=50)),
                ('aeCreatedDate', models.DateField()),
                ('aeDescription', models.CharField(max_length=200)),
                ('aeValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccDateFrom', models.DateField()),
                ('ccDateTo', models.DateField()),
                ('ccInitialCashValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalCash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalCheks', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalCreditCard', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalDebitCard', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalInflow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalLeftOverMoney', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalLackMoney', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalCashierInflow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalCashierCheks', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalCashierCreditCard', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closingCashTotalCashierDebitCard', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalOutflow', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotalReceivableAccounts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ccObservation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150)),
                ('companyRuc', models.CharField(max_length=15)),
                ('companyDescription', models.CharField(max_length=200)),
                ('companyType', models.CharField(max_length=100)),
                ('companyFirstFactureNumber', models.IntegerField(max_length=11)),
                ('companyFirstFactureNumber1', models.IntegerField(max_length=11)),
                ('companyFirstFactureNumber2', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detType', models.CharField(max_length=50)),
                ('detDescription', models.CharField(max_length=200)),
                ('detSalePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('detQuantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('detTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('detailDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeDate', models.DateTimeField()),
                ('feeValue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feeState', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hisCreatedDate', models.DateTimeField()),
                ('hisType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inSubtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inSubtotalIvazero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inSubtotalIva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inIva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inChange', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inCash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inAuthorizationDate', models.DateField()),
                ('inIssueTime', models.DateTimeField()),
                ('inNumber', models.CharField(max_length=200)),
                ('inDiscount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inIssueDate', models.DateField()),
                ('inState', models.CharField(max_length=50)),
                ('invoicePaymentMethod', models.CharField(max_length=50)),
                ('inPetitionName', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prFirstName', models.CharField(max_length=150)),
                ('prLastName', models.CharField(max_length=150)),
                ('prAddress', models.CharField(max_length=250)),
                ('prEmail', models.CharField(max_length=150)),
                ('prPhone', models.CharField(max_length=20)),
                ('prIdentification', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptIssueDate', models.DateTimeField()),
                ('ptState', models.BooleanField(default=False)),
                ('ptTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdDescription', models.CharField(max_length=200)),
                ('pdSalePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pdName', models.CharField(max_length=150)),
                ('pdCode', models.CharField(max_length=100)),
                ('pdBarcode', models.CharField(max_length=150)),
                ('pdIvaState', models.IntegerField(max_length=2)),
                ('pdStock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('productState', models.IntegerField(max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivableAccountDate', models.DateTimeField()),
                ('receivableAccountInterest', models.IntegerField(max_length=2)),
                ('receivableAccountInvoiceNumber', models.CharField(max_length=11)),
                ('receivableAccountAdvance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receivableAccountTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receivableAccountBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receivableAccountFee', models.CharField(max_length=11)),
                ('receivableAccountState', models.CharField(max_length=11)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolName', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_INVOICE_NUMBER', models.CharField(max_length=25)),
                ('IVA_VALUE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SECOND_INVOICE_NUMBER', models.CharField(max_length=25)),
                ('THIRD_INVOICE_NUMBER', models.CharField(max_length=25)),
                ('ACCURACY_VALUE', models.IntegerField(max_length=5)),
                ('AUTHORIZATION_NUMBER', models.CharField(max_length=25)),
                ('SHOW_PRINT_PREVIEW', models.BooleanField(default=False)),
                ('FACTURE_REPORT_SRC', models.CharField(max_length=250)),
                ('COMPANY_TYPE', models.CharField(max_length=50)),
                ('END_HOUR_JOURNEY', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.IntegerField(max_length=11)),
                ('tableDetails', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrName', models.CharField(max_length=50)),
                ('usrPassword', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='petition',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Table'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Person'),
        ),
        migrations.AddField(
            model_name='fee',
            name='receivableAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.ReceivableAccount'),
        ),
        migrations.AddField(
            model_name='detail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice'),
        ),
        migrations.AddField(
            model_name='detail',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Petition'),
        ),
        migrations.AddField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Product'),
        ),
        migrations.AddField(
            model_name='closingcash',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.History'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Company'),
        ),
    ]
