# Generated by Django 2.0 on 2017-12-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20171223_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Invoice'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Petition'),
        ),
    ]
